### ISSUE TITLE
Владение и обращение с оружием

### ISSUE THREAD

**Issue by Schaliemow** [keepseasy/Threads-of-Fate#2]
https://github.com/keepseasy/Threads-of-Fate/blob/a5ed547d2fa8c0cf7f37c0f98adf9acf71f9d333/hero-creation/development.tex#L10

По тексту Правил про *обращение с оружием* указано шесть раз, включая приведённый фрагмент. При этом ни в одном из фрагментов не содержится описания, как конкретно механика *обращения с оружием* должна работать в общем случае.

+ Например, мастерство в *обращении с оружием* **Высшего эльфа** увеличивает диапазон **Критического урона** на 1.
+ А сноровка **Полурослика** в *обращении с метательным оружием* также увеличивает диапазон **Критического урона** на 1 при использовании метательного оружия и пращи, но в этом случае ещё и улучшает **Меткость** персонажа с этим Атрибутом на 1.
+ Вершины мастерства **Человека без имени** в *обращении с огнестрельным оружием* увеличивают диапазон **Критического урона** на 1, добавляют **Бонус к повреждениям** оружия +1, увеличивают **Скорострельность** оружия на 1. В дополнение к этому, количество одновременно поражаемых огнестрельным оружием целей удваивается.
+ Трюк **Воинское мастерство** позволяет персонажу изучить все тонкости *обращения с оружием*, что, уже ожидаемо, расширяет диапазон **Критического урона**. Тем не менее, здесь содержится упоминание о том, что персонаж должен быть *знаком* с используемым оружием и ссылка в раздел «Оружие».

И только на 99-й странице читателя знакомят с механикой *владения различными видами оружия* (не путать с навыком **Владение оружием**!), которая устанавливает **Помеху** при проверках **Доблести** и **Меткости** при использовании оружия, отличного от выбранного на этапе создания персонажа[^1], если персонаж не научился *владеть оружием* за 2 **Очка опыта**.

[^1]: В тексте Правил фраза указана как `В начале игры герой должен выбрать число видов оружия, которыми он умеет пользоваться, равное |3 +МИн|`, достоверным допущением будет отнесение вопросов определения изначальных навыков, знаний и умений персонажа, включая, но не ограничиваясь «нулевой сессией», именно к этапу создания персонажа. Также уместно будет допустить, что `число видов оружия` - это именно перечисление конкретных наименований из таблиц оружия ближнего боя / вспомогательного и импровизированного оружия / дальнобойного оружия (прошлого, современного и будущего).

В связи с вышеизложенным имеются некоторые вопросы и предложения.

Отдавая себе отчет в том, что **Нити Судьбы** задумывались, в том числе, как разрешение вопросов, связанных с динамикой повествования (особенно, боевой части), всё же предлагаю:
+ разделить *владение оружием* и *обращение с оружием*, как различные элементы одной механики (в данном контексте, Первичный и Дополнительный);
+ Первичный элемент определить, как «знания персонажа о том, как эффективно использовать то или иное оружие, и связанное с такими знаниями базовое умение по применению указанного оружия безотносительно опыта его применения»;
+ фразы о *владении оружием* и *обращении с оружием* считать синонимичными и применять только по отношению к Первичному элементу;
+ определить Дополнительный элемент, как «природная предрасположенность (талант) и/или наличие достаточного практического опыта в применении определенного оружия, позволяющая (-ее, -ие) применять данное оружие существенно эффективнее уровня обученного и подготовленного пользователя»;
+ в пунктах Правил, где в настоящее время встречаются упоминания *обращения с оружием*, изложить текст в новой редакции, в соответствии с которой вместо *обращения с оружием* ввести унифицированное понятие **Воинское
мастерство |{наименование}|** и исключить одноимённый Трюк из Правил;
+ описать **Воинское мастерство** игромеханически, как расширение диапазона **Критического урона** на 1.
+ внести информацию о *владении различными видами оружия* и **Воинском мастерстве** в раздел 2.8 «Боевые характеристики»;
+ добавить в раздел 2.19 «Развитие героя» приобретение **Воинского мастерства  |{наименование}|** также за 2 **Очка опыта** с требованием наличия не менее 5 очков в навыке **Владение оружием**;
+ навык **Владение оружием** в целях сохранения преемственности редакций в настоящий момент оставить как есть, но обратить внимание, что навык **Обращение с животными** не является единым и для каждого вида животного приобретается отдельно.

В дополнение предлагаю также рассмотреть следующие вопросы:
+ в случае принятия вышеизложенной концепции, оставлять ли в Атрибутах дополнительные оружейные бонусы, или же для различных *типов*, *свойств* (а в отдельных интересных случаях и наименований) оружия прописать *специальный бонус*, например, в похожем виде `Метательное: +1 к Мт`?
+ требуются ли указания наименований оружия для **Высшего эльфа**, поскольку представленный в описании Атрибута архетипический образ generic-fantasy-эльфа исключает использование тяжелого или громоздкого (в «бытовом», не игромеханическом понимании) оружия? Схожий вопрос про полуросликов, метающих полноценные копья.

**Comment by keepseasy** [comment]
Мы с Ваней решили, что усложнение будет лишним, поэтому в следующих упоминание о владении конкретным видом оружия будет признано устаревшим - в том числе и Трюк Воинское мастерство.
В Атрибут Полурослик будут внесены уточняющие исправления, остальные Атрибуты остаются без изменений.
